import Foundation

// All times in the checks are local time; the suite therefore runs in any time zone.
timerChecks()
formattingChecks()
projectChecks()
budgetChecks()
multiContextChecks()
geoChecks()
breakChecks()
rateChecks()
expenseChecks()
retainerChecks()
travelChecks()
holidayChecks()
billingChecks()
idleChecks()
paidChecks()
importChecks()
tagChecks()
recurringChecks()
quickStartChecks()
backupChecks()
goalChecks()
heatmapChecks()
persistenceChecks()
reportChecks()
adapterChecks()
versionChecks()
invoiceChecks()
vatChecks()
ublChecks()
smtpChecks()

exit(Harness.summary())
